name = "AI NPC Talk - Zhipu Private"
description = "Private server mod: common NPCs can say short lines generated by a local Zhipu AI proxy."
author = "Private"
version = "0.1.0"

forumthread = ""

api_version = 10
api_version_dst = 10
dst_compatible = true
dont_starve_compatible = false
reign_of_giants_compatible = false
shipwrecked_compatible = false

all_clients_require_mod = true
client_only_mod = false
server_only_mod = false

configuration_options =
{
    {
        name = "npc_group_intelligent",
        label = "Intelligent NPC talk",
        options =
        {
            { description = "On", data = true },
            { description = "Off", data = false },
        },
        default = true,
    },
    {
        name = "npc_group_animals",
        label = "Animal talk",
        options =
        {
            { description = "On", data = true },
            { description = "Off", data = false },
        },
        default = true,
    },
    {
        name = "npc_group_monsters",
        label = "Monster talk",
        options =
        {
            { description = "On", data = true },
            { description = "Off", data = false },
        },
        default = true,
    },
    {
        name = "npc_group_ocean",
        label = "Ocean creature talk",
        options =
        {
            { description = "On", data = true },
            { description = "Off", data = false },
        },
        default = true,
    },
    {
        name = "min_interval_seconds",
        label = "Minimum interval",
        options =
        {
            { description = "20 seconds", data = 20 },
            { description = "40 seconds", data = 40 },
            { description = "60 seconds", data = 60 },
        },
        default = 20,
    },
    {
        name = "max_interval_seconds",
        label = "Maximum interval",
        options =
        {
            { description = "40 seconds", data = 40 },
            { description = "60 seconds", data = 60 },
            { description = "80 seconds", data = 80 },
        },
        default = 40,
    },
    {
        name = "talker_font_size",
        label = "Talk bubble font size",
        options =
        {
            { description = "16", data = 16 },
            { description = "20", data = 20 },
            { description = "24", data = 24 },
            { description = "28", data = 28 },
            { description = "32", data = 32 },
            { description = "36", data = 36 },
            { description = "40", data = 40 },
        },
        default = 24,
    },
    {
        name = "proxy_url",
        label = "Local proxy URL",
        options =
        {
            { description = "127.0.0.1:8765", data = "http://127.0.0.1:8765/say" },
            { description = "localhost:8765", data = "http://localhost:8765/say" },
        },
        default = "http://127.0.0.1:8765/say",
    },
    {
        name = "enable_logs",
        label = "Debug logs",
        options =
        {
            { description = "Off", data = false },
            { description = "On", data = true },
        },
        default = false,
    },
}
